name: Annotate Git Diff
description: Shows git diff between current and previous commit as a build annotation
author: github.com/mcncl
requirements:
  - git
configuration:
  properties:
    context:
      type: string
      default: "git-diff"
    format:
      type: string
      enum: ["markdown", "diff"]
      default: "markdown"
  additionalProperties: false
