env:
  BUILDKITE_PLUGINS_ALWAYS_CLONE_FRESH: "true"

steps:
  - label: ":shell: Tests"
    plugins:
      - plugin-tester#v1.1.1:
          folders:
            - tests

  - label: ":sparkles: Lint"
    plugins:
      - plugin-linter#v3.3.0:
          id: mcncl/annotate-git-diff

  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.4.0:
          files:
            - hooks/**
            - lib/**
